services:
  profile:
    build: 
      context: ./profile
    environment:
      DB_HOST: profile-db
      DB_PORT: 5432
      DB_NAME: profile
      DB_USERNAME: profileapp
      DB_PASSWORD: profilepassword
      SESSION_DB_HOST: session-db
      SESSION_DB_PORT: 27017
      SESSION_DB_NAME: session
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: profileapp
      RABBITMQ_PASSWORD: profilepassword
    depends_on:
      - session-db
      - profile-db
      - rabbitmq
    networks:
      - tasks_tracker
  
  task:
    build: 
      context: ./task
    environment:
      DB_HOST: task-db
      DB_PORT: 5432
      DB_NAME: task
      DB_USERNAME: taskapp
      DB_PASSWORD: taskpassword
      SESSION_DB_HOST: session-db
      SESSION_DB_PORT: 27017
      SESSION_DB_NAME: session
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: taskapp
      RABBITMQ_PASSWORD: taskpassword
    depends_on:
      - session-db
      - task-db
      - rabbitmq
    networks:
      - tasks_tracker
    
  profile-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: profile
      POSTGRES_USERNAME: profileapp
      POSTGRES_PASSWORD: profilepassword
    volumes:
      - profile-db-data:/var/lib/postgresql/data
    networks:
      - tasks_tracker
      
  task-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task
      POSTGRES_USERNAME: taskapp
      POSTGRES_PASSWORD: taskpassword
    volumes:
      - task-db-data:/var/lib/postgresql/data
    networks:
      - tasks_tracker
      
  session-db:
    image: mongo:latest
    volumes:
      - session-db-data:/var/lib/mongodb/data
    networks:
      - tasks_tracker

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpassword
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - tasks_tracker

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - profile
      - task
    networks:
      - tasks_tracker

networks:
  tasks_tracker:

volumes:
  profile-db-data:
  task-db-data:
  session-db-data:
