services:
  profile:
    build: 
      context: ./profile
    environment:
      DB_HOST: profile-db
      DB_PORT: 5432
      DB_NAME: profile
      DB_USERNAME: profileapp
      DB_PASSWORD: profilepassword
      SESSION_DB_HOST: session-db
      SESSION_DB_PORT: 27017
      SESSION_DB_NAME: session
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: profileapp
      RABBITMQ_PASSWORD: profilepassword
      REDIS_HOST: profile-redis
      REDIS_PORT: 6379
    secrets:
      - s3_endpoint
      - s3_region
      - s3_bucket_name
      - s3_access_key
      - s3_secret_key
    depends_on:
      - session-db
      - profile-db
      - rabbitmq
      - profile-redis
    networks:
      - tasks_tracker
  
  task:
    build: 
      context: ./task
    environment:
      DB_HOST: task-db
      DB_PORT: 5432
      DB_NAME: task
      DB_USERNAME: taskapp
      DB_PASSWORD: taskpassword
      SESSION_DB_HOST: session-db
      SESSION_DB_PORT: 27017
      SESSION_DB_NAME: session
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: taskapp
      RABBITMQ_PASSWORD: taskpassword
      REDIS_HOST: task-redis
      REDIS_PORT: 6379
    depends_on:
      - session-db
      - task-db
      - rabbitmq
      - task-redis
    networks:
      - tasks_tracker
    
  profile-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: profile
      POSTGRES_USERNAME: profileapp
      POSTGRES_PASSWORD: profilepassword
    volumes:
      - ./init-scripts/profile-db-init.sql:/docker-entrypoint-initdb.d/profile-db-init.sql
      - profile-db-data:/var/lib/postgresql/data
    networks:
      - tasks_tracker
      
  task-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: task
      POSTGRES_USERNAME: taskapp
      POSTGRES_PASSWORD: taskpassword
    volumes:
      - ./init-scripts/task-db-init.sql:/docker-entrypoint-initdb.d/task-db-init.sql
      - task-db-data:/var/lib/postgresql/data
    networks:
      - tasks_tracker
      
  session-db:
    image: mongo:latest
    volumes:
      - ./init-scripts/session-db-init.js:/docker-entrypoint-initdb.d/session-db-init.js
      - session-db-data:/data/db
    networks:
      - tasks_tracker

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpassword
    volumes:
      - ./init-scripts/definitions.json:/etc/rabbitmq/definitions.json
      - ./rabbitmq:/var/lib/rabbitmq
    command: rabbitmq-server --definitions /etc/rabbitmq/definitions.json
    networks:
      - tasks_tracker

  profile-redis:
    image: redis:latest
    volumes:
      - profile-redis-data:/data
    networks:
      - tasks_tracker

  task-redis:
    image: redis:latest
    volumes:
      - task-redis-data:/data
    networks:
      - tasks_tracker

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - profile
      - task
    networks:
      - tasks_tracker

networks:
  tasks_tracker:

volumes:
  profile-db-data:
  task-db-data:
  session-db-data:
  profile-redis-data:
  task-redis-data:

secrets:
  s3_endpoint:
    file: ./s3_endpoint.txt
  s3_bucket_name:
    file: ./s3_bucket_name.txt
  s3_region:
    file: ./s3_region.txt
  s3_access_key:
    file: ./s3_access_key.txt
  s3_secret_key:
    file: ./s3_secret_key.txt
